#!/bin/bash

echo "🚨 Google Auth Origin 錯誤修復腳本"
echo "=================================="
echo ""
echo "問題: The given origin is not allowed for the given client ID"
echo "原因: localhost:5173 沒有被授權使用 Google Client ID"
echo ""
echo "🔧 修復步驟:"
echo "1. 前往 Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials?project=chainy-473820"
echo ""
echo "2. 找到 OAuth 2.0 Client ID:"
echo "   1079648073253-kueo7mpri415h10dsc0fldeoecp878l6.apps.googleusercontent.com"
echo ""
echo "3. 點擊編輯 (鉛筆圖示)"
echo ""
echo "4. 在 '授權的 JavaScript 來源' 中添加:"
echo "   ✅ http://localhost:5173"
echo "   ✅ http://127.0.0.1:5173"
echo ""
echo "5. 在 '授權的重定向 URI' 中添加:"
echo "   ✅ http://localhost:5173/callback"
echo "   ✅ http://localhost:5173/google-auth-callback.html"
echo "   ✅ http://localhost:5173"
echo ""
echo "6. 點擊 '儲存'"
echo ""
echo "⏳ 等待 5-10 分鐘讓配置生效"
echo ""
echo "🧪 修復後測試:"
echo "1. 重新整理頁面: http://localhost:5173"
echo "2. 檢查 Console 是否還有錯誤"
echo "3. 點擊 Google 登錄按鈕測試"
echo ""
echo "📱 如果還有問題，請檢查:"
echo "- OAuth 同意畫面是否設置為 '測試' 模式"
echo "- 是否添加了測試使用者"
echo "- 是否啟用了必要的 API"
